In [21]:
import pandas as pd
import numpy as np
from bs4 import BeautifulSoup 
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction import stop_words
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score

In [22]:
df = pd.read_csv('good_data.csv')

In [23]:
df.isna().sum()

Unnamed: 0    0
title         0
subreddit     0
class         0
dtype: int64

In [24]:
X = df['title']
y = df['class']

In [25]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [26]:
cvec = CountVectorizer(stop_words='english', ngram_range=(2, 6))
X_train = cvec.fit_transform(X_train)

In [27]:
X_train.todense()

matrix([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [28]:
X_test = cvec.transform(X_test)

In [29]:
model_lr = LogisticRegression()
print(cross_val_score(model_lr, X_train, y_train).mean())
model_lr.fit(X_train, y_train)
model_lr.predict(X_test)

0.9471982567631171


array([1, 1, 0, ..., 0, 0, 1])

In [30]:
model_lr.score(X_test, y_test)

0.9756986634264885

In [31]:
coefs = model_lr.coef_

In [32]:
names_1 = cvec.get_feature_names()

In [33]:
coefs[0]

array([-0.05796197, -0.05796197, -0.05796197, ..., -0.05982459,
       -0.05982459, -0.05982459])

In [34]:
names = pd.DataFrame({'coefs':coefs[0], 'names':names_1})

In [35]:
names

coefs                                         names
0     -0.057962                                   000 bottles
1     -0.057962                             000 bottles water
2     -0.057962                          000 bottles water 20
3     -0.057962                      000 bottles water 20 000
4     -0.057962                 000 bottles water 20 000 hats
5     -0.057962                                      000 hats
6     -0.057962                             000 hats tomorrow
7     -0.057962                    000 hats tomorrow valencia
8     -0.057962              000 hats tomorrow valencia derby
9     -0.057962        000 hats tomorrow valencia derby kicks
10    -0.026761                                    000 mellis
11    -0.026761                              000 mellis given
12    -0.026761                          000 mellis given 500
13    -0.026761                     000 mellis given 500 fine
14    -0.061349                                   000 spanish
15    -0.061349                             000 spanish flags
16    -0.036188                 000 spanish flags distributed
17    -0.025162                      000 spanish flags handed
18    -0.025162               000 spanish flags handed league
19    -0.025162          000 spanish flags handed league does
20    -0.041336                                      000 week
21    -0.041336                             000 week defender
22     0.012721                                  008m russell
23     0.012721                           008m russell wilson
24     0.012721                      008m russell wilson 912k
25     0.012721               008m russell wilson 912k calais
26     0.012721      008m russell wilson 912k calais campbell
27    -0.111210                                         02 09
28    -0.080016                                      02 09 18
29    -0.031194                                    02 09 2018
...         ...                                           ...
66255 -0.055029       zvezda currently tied points look table
66256 -0.070521                                zvezdan terzić
66257 -0.070521                        zvezdan terzić general
66258 -0.070521                zvezdan terzić general manager
66259 -0.070521            zvezdan terzić general manager red
66260 -0.070521       zvezdan terzić general manager red star
66261 -0.057283                                zwickau german
66262 -0.057283                    zwickau german translation
66263 -0.057283           zwickau german translation comments
66264 -0.020799                                  zwolle dutch
66265 -0.020799                       zwolle dutch eredivisie
66266  0.044691                                  zylstra make
66267  0.044691                          zylstra make vikings
66268  0.044691                   zylstra make vikings roster
66269  0.044691         zylstra make vikings roster hamstring
66270  0.044691  zylstra make vikings roster hamstring issues
66271 -0.157642                                  éder militão
66272 -0.157642                           éder militão called
66273 -0.157642                    éder militão called brazil
66274 -0.157642              éder militão called brazil squad
66275 -0.157642      éder militão called brazil squad replace
66276 -0.258343                                  équipe picks
66277 -0.258343                            équipe picks ligue
66278 -0.258343                    équipe picks ligue players
66279 -0.258343               équipe picks ligue players week
66280 -0.059825                                 škriniar wait
66281 -0.059825                            škriniar wait play
66282 -0.059825                  škriniar wait play champions
66283 -0.059825           škriniar wait play champions league
66284 -0.059825      škriniar wait play champions league face

[66285 rows x 2 columns]

In [36]:
names.sort_values('coefs').head()

coefs             names
34901 -2.381696      match thread
44114 -1.876069    premier league
5825  -1.544312  barcelona huesca
46434 -1.502512       real madrid
37508 -1.382399  nacional benfica

In [37]:
names.sort_values('coefs').tail()

coefs           names
30503  1.169409         le veon
43985  1.184377  practice squad
49030  1.389989      round pick
53616  1.441287     source said
29211  2.394089     khalil mack

In [19]:
#names['names'] = 'messi'